# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Copy only gateway source
COPY cmd/gateway ./cmd/gateway
COPY internal/middlewares ./internal/middlewares
COPY internal/packages ./internal/packages
COPY internal/services/v1/user ./internal/services/v1/user

RUN go build -o gateway ./cmd/gateway

# Final stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/gateway .
EXPOSE 2000
CMD ["./gateway"]
