// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "dev@astrovia.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/agents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Get all agent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.Agent"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create new agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Create agent",
                "parameters": [
                    {
                        "description": "Agent info",
                        "name": "agent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.Agent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.Agent"
                        }
                    }
                }
            }
        },
        "/v1/agents/public": {
            "get": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Get all agent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.Agent"
                            }
                        }
                    }
                }
            }
        },
        "/v1/agents/public/{id}": {
            "get": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Get agent public by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Agent"
                        }
                    }
                }
            }
        },
        "/v1/agents/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Get agent by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Agent"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Update agent by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Update agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Agent info",
                        "name": "agent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.Agent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Agent"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Delete agent by ID",
                "tags": [
                    "Agents"
                ],
                "summary": "Delete agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/astro-zenith/auto-caption": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of autocaption",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCaption"
                ],
                "summary": "Get all autocaption",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.AutoCaption"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create new autocaption",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCaption"
                ],
                "summary": "Create autocaption",
                "parameters": [
                    {
                        "description": "AutoCaption info",
                        "name": "autocaption",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AutoCaption"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.AutoCaption"
                        }
                    }
                }
            }
        },
        "/v1/astro-zenith/auto-caption/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single autocaption",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCaption"
                ],
                "summary": "Get autocaption by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AutoCaption ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AutoCaption"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Update autocaption by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoCaption"
                ],
                "summary": "Update autocaption",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AutoCaption ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AutoCaption info",
                        "name": "autocaption",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AutoCaption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AutoCaption"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Delete autocaption by ID",
                "tags": [
                    "AutoCaption"
                ],
                "summary": "Delete autocaption",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AutoCaption ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/astro-zenith/auto-clip": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of autoclip",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoClips"
                ],
                "summary": "Get all autoclip",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.AutoClip"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create new autoclip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoClips"
                ],
                "summary": "Create autoclip",
                "parameters": [
                    {
                        "description": "AutoClip info",
                        "name": "autoclip",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AutoClip"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.AutoClip"
                        }
                    }
                }
            }
        },
        "/v1/astro-zenith/auto-clip/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single autoclip",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoClips"
                ],
                "summary": "Get autoclip by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AutoClip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AutoClip"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Update autoclip by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoClips"
                ],
                "summary": "Update autoclip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AutoClip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AutoClip info",
                        "name": "autoclip",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AutoClip"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AutoClip"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Delete autoclip by ID",
                "tags": [
                    "AutoClips"
                ],
                "summary": "Delete autoclip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AutoClip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/generate-token": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Generate token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authentication",
                "parameters": [
                    {
                        "description": "Auth info",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.Auth"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    },
                    {
                        "X-DeviceId": []
                    }
                ],
                "description": "Logout APP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "RefreshToken info",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    },
                    {
                        "X-DeviceId": []
                    }
                ],
                "description": "Logout All Device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout All Device",
                "parameters": [
                    {
                        "description": "RefreshToken info",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh-token": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    },
                    {
                        "X-DeviceId": []
                    }
                ],
                "description": "Refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh Tokens",
                "parameters": [
                    {
                        "description": "RefreshToken info",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.RefreshToken"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/payment/order-public": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create Order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Create order for subscription",
                "parameters": [
                    {
                        "description": "Order info",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.CreateOrderRequest"
                        }
                    }
                }
            }
        },
        "/v1/payment/payment-method/{id}": {
            "get": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of payment method",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Get all payment method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pricing ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.Payment"
                            }
                        }
                    }
                }
            }
        },
        "/v1/pricing": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of pricing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pricing"
                ],
                "summary": "Get all pricing",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.Pricing"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pricing"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "Pricing info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.Pricing"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.Pricing"
                        }
                    }
                }
            }
        },
        "/v1/pricing/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pricing"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pricing ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Pricing"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Update user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pricing"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pricing ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pricing info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.Pricing"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Pricing"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Delete user by ID",
                "tags": [
                    "Pricing"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pricing ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/user-agents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of user agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAgents"
                ],
                "summary": "Get all user agent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.UserAgent"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create new user agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAgents"
                ],
                "summary": "Create user agent",
                "parameters": [
                    {
                        "description": "UserAgent info",
                        "name": "useragent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.UserAgent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.UserAgent"
                        }
                    }
                }
            }
        },
        "/v1/user-agents/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single user agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAgents"
                ],
                "summary": "Get user agent by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserAgent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UserAgent"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Update user agent by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAgents"
                ],
                "summary": "Update user agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserAgent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserAgent info",
                        "name": "useragent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.UserAgent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UserAgent"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Delete user agent by ID",
                "tags": [
                    "UserAgents"
                ],
                "summary": "Delete user agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserAgent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get list of users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Create new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                }
            }
        },
        "/v1/users/check": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Check users exist",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Check users exist by email",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.User"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users/create-password": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "create password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create password for user",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.User"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users/resend-verification": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "resend OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Resend OTP",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.User"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users/verify-verification": {
            "post": {
                "security": [
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "verify otp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.User"
                            }
                        }
                    }
                }
            }
        },
        "/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Get single user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Update user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.User"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "X-Signature": []
                    },
                    {
                        "X-Timestamp": []
                    }
                ],
                "description": "Delete user by ID",
                "tags": [
                    "Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.Agent": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "routes.Auth": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "routes.AutoCaption": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "routes.AutoClip": {
            "type": "object",
            "properties": {
                "thumbnail": {
                    "type": "string"
                },
                "video_title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        },
        "routes.CreateOrderRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "payment_method",
                "phone",
                "pricing_id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pricing_id": {
                    "type": "string"
                }
            }
        },
        "routes.Payment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "datetime": {
                    "type": "string"
                },
                "merchantcode": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "routes.Pricing": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "routes.RefreshToken": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "routes.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "routes.UserAgent": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Format: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "X-DeviceId": {
            "description": "DeviceId untuk validasi request",
            "type": "apiKey",
            "name": "X-DeviceId",
            "in": "header"
        },
        "X-Signature": {
            "description": "Signature HMAC SHA256 untuk validasi integritas request",
            "type": "apiKey",
            "name": "X-Signature",
            "in": "header"
        },
        "X-Timestamp": {
            "description": "Timestamp UTC format RFC3339 (contoh: 2025-11-03T09:10:00Z)",
            "type": "apiKey",
            "name": "X-Timestamp",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Astrovia Gateway API",
	Description:      "API Gateway Astrovia AI.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
